spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      # base-url:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          # https://bailian.console.aliyun.com/?tab=model#/model-market
          model: qwen-plus
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.ai.api
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn